AWSTemplateFormatVersion: '2010-09-09'
Description: 'NAT Gateway configuration for private subnet internet access'

Parameters:
  VPCStackName:
    Type: String
    Description: Name of the VPC stack
    Default: 'dev-vpc'
  
  SubnetStackName:
    Type: String
    Description: Name of the subnet stack
    Default: 'dev-subnets'
  
  NatGatewayStrategy:
    Type: String
    Description: NAT Gateway deployment strategy
    Default: 'single'
    AllowedValues:
      - 'none'
      - 'single'
      - 'per-az'
  
  Environment:
    Type: String
    Description: Environment name
    Default: 'dev'

Conditions:
  CreateNATGateway: !Not [!Equals [!Ref NatGatewayStrategy, 'none']]
  CreateSingleNAT: !Equals [!Ref NatGatewayStrategy, 'single']
  CreatePerAZNAT: !Equals [!Ref NatGatewayStrategy, 'per-az']

Resources:
  # Elastic IPs for NAT Gateways
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Condition: CreateNATGateway
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-nat-eip-1'
        - Key: Environment
          Value: !Ref Environment

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    Condition: CreatePerAZNAT
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-nat-eip-2'
        - Key: Environment
          Value: !Ref Environment

  # NAT Gateways
  NatGateway1:
    Type: AWS::EC2::NatGateway
    Condition: CreateNATGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId:
        Fn::ImportValue: !Sub '${SubnetStackName}-PublicSubnet1Id'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-nat-1'
        - Key: Environment
          Value: !Ref Environment

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Condition: CreatePerAZNAT
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId:
        Fn::ImportValue: !Sub '${SubnetStackName}-PublicSubnet2Id'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-nat-2'
        - Key: Environment
          Value: !Ref Environment

  # Private Route Tables
  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Condition: CreateNATGateway
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPCId'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-rt-1'
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Condition: CreatePerAZNAT
    Properties:
      VpcId:
        Fn::ImportValue: !Sub '${VPCStackName}-VPCId'
      Tags:
        - Key: Name
          Value: !Sub '${Environment}-private-rt-2'
        - Key: Environment
          Value: !Ref Environment
        - Key: Type
          Value: Private

  # Default routes for private subnets
  DefaultPrivateRoute1:
    Type: AWS::EC2::Route
    Condition: CreateNATGateway
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway1

  DefaultPrivateRoute2:
    Type: AWS::EC2::Route
    Condition: CreatePerAZNAT
    Properties:
      RouteTableId: !Ref PrivateRouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway2

  # Route table associations
  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateNATGateway
    Properties:
      RouteTableId: !Ref PrivateRouteTable1
      SubnetId:
        Fn::ImportValue: !Sub '${SubnetStackName}-PrivateSubnet1Id'

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Condition: CreateNATGateway
    Properties:
      RouteTableId: !If [CreatePerAZNAT, !Ref PrivateRouteTable2, !Ref PrivateRouteTable1]
      SubnetId:
        Fn::ImportValue: !Sub '${SubnetStackName}-PrivateSubnet2Id'

Outputs:
  NatGateway1Id:
    Condition: CreateNATGateway
    Description: NAT Gateway 1 ID
    Value: !Ref NatGateway1
    Export:
      Name: !Sub '${AWS::StackName}-NatGateway1Id'
  
  NatGateway2Id:
    Condition: CreatePerAZNAT
    Description: NAT Gateway 2 ID
    Value: !Ref NatGateway2
    Export:
      Name: !Sub '${AWS::StackName}-NatGateway2Id'
  
  PrivateRouteTable1Id:
    Condition: CreateNATGateway
    Description: Private Route Table 1 ID
    Value: !Ref PrivateRouteTable1
    Export:
      Name: !Sub '${AWS::StackName}-PrivateRouteTable1Id'
  
  PrivateRouteTable2Id:
    Condition: CreatePerAZNAT
    Description: Private Route Table 2 ID
    Value: !Ref PrivateRouteTable2
    Export:
      Name: !Sub '${AWS::StackName}-PrivateRouteTable2Id'